server:
  port: 8084
  servlet:
    session:
      timeout: 54000

spring:
  main:
    allow-bean-definition-overriding: true

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ENDPOINT}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: redis.interviewbㅁank
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  swagger:
    server:
      url: https://bproduction.interviewbank.net

  oauth2:
    client:
      registration:
        google:
          auth-uri: https://accounts.google.com/o/oauth2/v2/auth
          token-uri: https://oauth2.googleapis.com/token
          profile-uri: https://www.googleapis.com/auth/userinfo
          redirect-uri: https://fstaging.interviewbank.net/oauth2/google/redirect
        naver:
          auth-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          profile-uri: https://openapi.naver.com/v1/nid/me
          redirect-uri: https://fstaging.interviewbank.net/oauth2/naver/redirect
        kakao:
          auth-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          profile-uri: https://kapi.kakao.com/v2/user/me
          redirect-uri: https://fstaging.interviewbank.net/oauth2/kakao/redirect

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
