INSERT INTO job_category (id, name, parent_id) VALUES (1, '개발', null);
INSERT INTO job_category (id, name, parent_id) VALUES (2, 'R&D', null);
INSERT INTO job_category (id, name, parent_id) VALUES (3, '디자인', null);
INSERT INTO job_category (id, name, parent_id) VALUES (4, '기획/PM', null);
INSERT INTO job_category (id, name, parent_id) VALUES (5, '마케팅', null);
INSERT INTO job_category (id, name, parent_id) VALUES (6, '기타', null);
INSERT INTO job_category (id, name, parent_id) VALUES (7, '백엔드', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (8, '프런트엔드', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (9, '안드로이드', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (10, 'IOS', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (11, '모바일', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (12, 'DevOps', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (13, 'QA', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (14, '게임', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (15, 'AI', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (16, 'UI', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (17, 'UX', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (18, '웹 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (19, '그래픽 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (20, '아트 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (21, '모바일 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (22, '광고 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (23, 'BI/BX 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (24, '모션 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (25, '3D 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (26, '컨텐츠 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (27, '아트디렉터', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (28, '공간 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (29, '캐릭터 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (30, '편집 디자인', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (31, '기타', 3);
INSERT INTO job_category (id, name, parent_id) VALUES (32, 'DBA', 1);
INSERT INTO job_category (id, name, parent_id) VALUES (33, '기타', 1);

