version: "3"

networks:
  backend:

services:
  app:
    build: ../
    restart: always
    env_file:
      - ../staging.env
    expose:
      - "8084"
    volumes:
      - ../logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      backend:
        aliases:
          - app.interviewbank.net

  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/staging:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      backend:
    depends_on:
      - app
      - grafana
      - prometheus

  db:
    image: mysql:8.0
    container_name: mysql
    expose:
      - "3306"
    env_file:
      - ../staging.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../datadir/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - db.interviewbank

  redis:
    image: redis:7.0
    container_name: redis
    expose:
      - "6379"
    command:
      - redis-server
    volumes:
      - ../datadir/redis:/data
    networks:
      backend:
        aliases:
          - redis.interviewbank

  prometheus:
    image: prom/prometheus
    expose:
      - "9090"
    user: "0:0"
    volumes:
      - ../staging-yml/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus:/prometheus
    networks:
      backend:
        aliases:
          - prometheus.interviewbank

  grafana:
    image: "grafana/grafana"
    expose:
      - "3000"
    user: "0:0"
    volumes:
      - ../staging-yml/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana:/var/lib/grafana
    networks:
      backend:
        aliases:
          - grafana.interviewbank

  backup:
    build: ../db-backup
    env_file:
      - ../db-backup/backup.env
    volumes:
      - ../db-backup:/backup
    depends_on:
      - db
    networks:
      backend:

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      backend:
        aliases:
          - loki.interviewbank

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ../logs:/var/log
      - ../staging-yml/promtail.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      backend:
