version: "3"

networks:
  backend:

services:
  app:
    build: ../
    restart: always
    env_file:
      - ../staging.env
    expose:
      - "8084"
    depends_on:
      - db
      - redis
    networks:
      backend:
        aliases:
          - app.interviewbank.net

  nginx:
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/staging:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      backend:
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../datadir/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - db.interviewbank

  redis:
    image: redis:7.0
    container_name: redis
    expose:
      - "6379"
    command:
     - redis-server
    volumes:
      - ../datadir/redis:/data
    networks:
      backend:
        aliases:
        - redis.interviewbank
