on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches: [ "staging" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 17
          distribution: adopt
 
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
 
      - name: Test with Gradle
        run: ./gradlew --info test
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml
